export const HIGH_RISK_COLOR = '#F8A58E';
export const MEDIUM_RISK_COLOR = '#E4D96F';
export const LOW_RISK_COLOR = '#ADEBB3';

export const RISK_COLOR_LIST = [HIGH_RISK_COLOR, MEDIUM_RISK_COLOR, LOW_RISK_COLOR];

export const HIGH_STATUS_SCORE = 81;
export const MEDIUM_STATUS_SCORE = 61;
export const LOW_STATUS_SCORE = 0;

export const STATUS_SCORE_LIST = [HIGH_STATUS_SCORE, MEDIUM_STATUS_SCORE, LOW_STATUS_SCORE];
